force auth

diff --git a/.github/workflows/adhoc.yml b/.github/workflows/adhoc.yml
--- a/.github/workflows/adhoc.yml
+++ b/.github/workflows/adhoc.yml
@@ -39,8 +39,8 @@ jobs:
       if: steps.cache-browser.outputs.cache-hit != 'true'
       run: |
         playwright install chromium
-    # - name: Auth check
-    #   run: |
-    #     [ -d "~/.config/esporifai/" ] && rm -rf ~/.config/esporifai/ || echo "config not found"
+    - name: Auth check
+      run: |
+        [ -d "~/.config/esporifai/" ] && rm -rf ~/.config/esporifai/ || echo "config not found"
         
-    #     esporifai auth --force
+        esporifai auth --force
